pub mod agent;
pub mod agent_dir;
pub mod config;
pub mod conversation;
pub mod daemon;
pub mod debug;
pub mod discovery;
pub mod embedding;
pub mod error;
pub mod llm;
pub mod memory;
pub mod message;
pub mod messaging;
pub mod observe;
pub mod repl;
pub mod retry;
pub mod runtime;
pub mod socket_api;
pub mod supervision;
pub mod tool;
pub mod tool_registry;
pub mod tools;

// Re-export main types for convenience
pub use agent::{Agent, ThinkOptions, ThinkResult, ReflectionConfig, ReflectionResult, AutoMemoryConfig};
pub use embedding::{EmbeddingClient, EmbeddingError, cosine_similarity};
pub use error::{AgentError, ToolError, ErrorContext};
pub use memory::{Memory, MemoryEntry, MemoryError, InMemoryStore, SqliteMemory, SemanticMemoryStore, SemanticMemoryEntry, SaveResult, extract_remember_tags, build_memory_injection, format_age};
pub use message::Message;
pub use messaging::{AgentMessage, AgentMailbox, MessageRouter, MessagingError};
pub use observe::{Observer, Event, ConsoleObserver, MetricsCollector, MetricsSnapshot, MultiObserver};
pub use retry::{RetryPolicy, RetryResult, with_retry};
pub use runtime::Runtime;
pub use tool::{Tool, ToolInfo};
pub use tools::{SendMessageTool, ListAgentsTool};
pub use llm::{LLM, ChatMessage, ToolSpec, ToolCall, LLMResponse, LLMError, OpenAIClient, AnthropicClient, OllamaClient, UsageInfo, strip_thinking_tags};
pub use supervision::{ChildHandle, ChildConfig, ChildStatus};
pub use tool_registry::{ToolRegistry, ToolDefinition, ToolRegistryError};
pub use conversation::{ConversationStore, Conversation, ConversationMessage, Participant, PendingNotification, ConversationError, canonical_1to1_id, canonical_group_id, parse_mentions, expand_all_mention, notify_mentioned_agents, notify_mentioned_agents_parallel, NotifyResult};
